import "~/styles/globals.css";

import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "clar1k - software engineer",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-theme-dark font-mono text-theme-light">
        {children}
      </body>
    </html>
  );
}
